### ISSUE TITLE
Finish replacing addDidBeginWaitingForReaderInputListener

### ISSUE THREAD

**Issue by ericvicenti** [theopolisme/react-native-stripe-terminal#11]
I think this is an old API, still used by `hooks.js`, causing an exception for me because the method no longer exists on `StripeTerminal`:

https://github.com/theopolisme/react-native-stripe-terminal/search?q=addDidBeginWaitingForReaderInputListener&unscoped_q=addDidBeginWaitingForReaderInputListener

**Comment by theopolisme** [comment]
Righto, need to fix this up and also work on documentation for hooks as well as connection manager. Will track that as a separate issue.

**Comment by fardeenpanjwaniucmouli** [comment]
I'm facing this issue but I'm not using hooks. Any insights? Can I open a separate issue with my code block, podfile, etc?

**Comment by theopolisme** [comment]
Hi there, that method has been deprecated by Stripe in the v1 release of terminal, but I have not yet updated the docs to reflect this. You should use `addDidRequestReaderInputListener`and `addDidRequestReaderDisplayMessageListener` instead. I'll try to push an update to the documentation (with updated examples too) within the next week. Sorry for the confusion!

**Comment by fardeenpanjwaniucmouli** [comment]
Thanks for replying so quick! I replaced the methods and now it doesn't throw any errors but when I try to use a card on the machine(ChipperTM 2X BT), the app doesn't respond at all. It's expected to render and alert. This is my code:
`
       StripeTerminal.addDidRequestReaderInputListener(async ({text}) => {
            alert(text)
        });

        StripeTerminal.addDidRequestReaderDisplayMessageListener(({text}) => {
            alert(text);
        });
`
But nothing happens when I try to swipe, dip or tap the test card on the reader. Can you please help. Thanks!

**Comment by fardeenpanjwaniucmouli** [comment]
any update?

**Comment by fardeenpanjwaniucmouli** [comment]
@theopolisme has there been any updates/developments? The issue has put a halt on our application's production. An ETA on the issue would be a great help, too! Thanks!
