### ISSUE TITLE
build failure: StripeTerminal.h not found

### ISSUE THREAD

**Issue by rothskeller** [theopolisme/react-native-stripe-terminal#2]
I have just installed Stripe's SDK and react-native-stripe-terminal following the posted instructions, but the resulting project fails to build with this error:

```
info CompileC /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: RNStripeTerminal)
    cd /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Index/DataStore -iquote /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-generated-files.hmap -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-own-target-headers.hmap -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-all-non-framework-target-headers.hmap -ivfsoverlay /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/all-product-headers.yaml -iquote /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-project-headers.hmap -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Products/Debug-iphonesimulator/include -I/Users/stever/src/orders/AtTheDoor/node_modules/ios/Pods/Headers/Public -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/stever/src/orders/AtTheDoor/React -I/Users/stever/src/orders/AtTheDoor/node_modules/react-native/React -I/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/Example/ios/Pods/Headers/Public/StripeTerminal -I/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/Example/node_modules/react-native/React -I/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/Example/ios/Pods -I/Users/theopatt/Documents/Projects/pos-dev/app/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources-normal/x86_64 -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources/x86_64 -I/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources -F/Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.d --serialize-diagnostics /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.dia -c /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m -o /Users/stever/src/orders/AtTheDoor/ios/build/AtTheDoor/Build/Intermediates.noindex/RNStripeTerminal.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o

info In file included from /Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:1:
/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.h:12:9: fatal error: 'StripeTerminal.h' file not found

info #import "StripeTerminal.h"
        ^~~~~~~~~~~~~~~~~~
```

Looking into this, I find that it should be able to access StripeTerminal.h via the `-I/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/Example/ios/Pods/Headers/Public/StripeTerminal`, since that directory contains a `StripeTerminal/StripeTerminal.h`.  However, the `StripeTerminal/StripeTerminal.h` in that directory is a symbolic link to `../../../../StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/StripeTerminal.h`, and that is a broken link.  The correct symbol link, looking at how things got installed on my system, would be `../../../../../../../../../ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers/StripeTerminal.h`.  And the same seems to be true for all of the other symbolic links in that directory.

I don't know squat about building iOS apps — if I did, I probably wouldn't be using React Native :-) — so I don't know how to track down the root cause of this problem or how best to fix it.  Help would be greatly appreciated.

(FWIW, this is using version 1.0.0 of the Stripe Terminal SDK, and the top of trunk version of react-native-stripe-terminal as of the timestamp of this issue.)

**Comment by rothskeller** [comment]
Followup:  I hacked around the above issue:  I noticed that your include path included a hardcoded `/Users/theopatt/Documents/Projects/pos-dev/app/ios/Pods/StripeTerminal/Carthage/Build/iOS/StripeTerminal.framework/Headers`, so I changed that in my local copy to the equivalent hard-coded path for my project, and it did get past the error I reported above.  Clearly having a hard-coded path on your local disk as part of your distribution doesn't work well.  :-)

**Comment by theopolisme** [comment]
Thanks for spotting this! Can you make a pull request with the fix to help other folks? :)

**Comment by HiteshR90** [comment]
@rothskeller i am still facing same issue can you please help me on that

**Comment by theopolisme** [comment]
Hi @HiteshR90, what is the error you're seeing / did you ensure you were using the latest version of the master branch?

**Comment by HiteshR90** [comment]
@theopolisme thanks for quick reply yes I am using latest master branch. steps which I followed as below. 

steps I followed
1) react-native init AwesomeProject
2) add pod 'StripeTerminal', '1.0.0' to pod file
3) pod install from ios folder
4) npm install git+https://github.com/theopolisme/react-native-stripe-terminal.git --save
5) react-native link react-native-stripe-terminal
6) pod install from ios folder
7) react-native run-ios
 which give me error as below

 CreateBuildDirectory /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Products (in target: React-RCTAnimation)
    cd /Users/hitesh/Desktop/react/AwesomeProject/ios/Pods
    builtin-create-build-directory /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Products

CreateBuildDirectory /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex (in target: React-RCTAnimation)
    cd /Users/hitesh/Desktop/react/AwesomeProject/ios/Pods
    builtin-create-build-directory /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex

CompileC /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target: RNStripeTerminal)
    cd /Users/hitesh/Desktop/react/AwesomeProject/ios/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Index/DataStore -iquote /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-generated-files.hmap -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-own-target-headers.hmap -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-all-target-headers.hmap -iquote /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/RNStripeTerminal-project-headers.hmap -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/RNStripeTerminal/include -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Private -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Private/RNStripeTerminal -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/DoubleConversion -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/RNStripeTerminal -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-Core -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-DevSupport -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTActionSheet -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTAnimation -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTBlob -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTImage -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTLinking -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTNetwork -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTSettings -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTText -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTVibration -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-RCTWebSocket -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-cxxreact -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-fishhook -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-jsi -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/React-jsinspector -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/glog -I/Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Headers/Public/yoga -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources-normal/x86_64 -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources/x86_64 -I/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/DerivedSources -F/Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Products/Debug-iphonesimulator/RNStripeTerminal -include /Users/hitesh/Desktop/react/AwesomeProject/ios/Pods/Target\ Support\ Files/RNStripeTerminal/RNStripeTerminal-prefix.pch -MMD -MT dependencies -MF /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.d --serialize-diagnostics /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.dia -c /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m -o /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o
In file included from /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:1:
/Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.h:12:9: fatal error: 'StripeTerminal.h' file not found
#import "StripeTerminal.h"
        ^~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **


The following build commands failed:
	CompileC /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by rothskeller** [comment]
@HiteshR90 I found that the `Podfile` that results from `react-native init` is not actually correct.  [This article](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies) describes what the `Podfile` should really look like.  The build error you quoted went away for me when I fixed the `Podfile`.

For your reference, here's my complete `Podfile`.  Of course, some of it is specific to my app and may not be needed for you.  But I think yours should be identical (other than target name) at least up through the `Folly` line.

```
target 'AtTheDoor' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'StripeTerminal', '1.0.0'
  pod 'Stripe', '~> 14.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', :subspecs => [
    'BarcodeDetectorMLKit',
  ]
end
```

**Comment by HiteshR90** [comment]
@rothskeller I have make pod file like above but still I am facing same issue.

info In file included from /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m:1:
/Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.h:12:9: fatal error: 'StripeTerminal.h' file not found

info #import "StripeTerminal.h"
        ^~~~~~~~~~~~~~~~~~

info 1 error generated.

And 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening AwesomeProject.xcworkspace

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/hitesh/Desktop/react/AwesomeProject/ios/build/AwesomeProject/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNStripeTerminal.build/Objects-normal/x86_64/RNStripeTerminal.o /Users/hitesh/Desktop/react/AwesomeProject/node_modules/react-native-stripe-terminal/ios/RNStripeTerminal.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
. Run CLI with --verbose flag for more details.

**Comment by rothskeller** [comment]
@HiteshR90 I am sorry to hear that the Podfile change didn't solve your issue.  I don't know what else to suggest to you, since that is what solved it for me.  If it helps, you're welcome to look at [my source code](https://github.com/scholacantorum/orders/tree/master/AtTheDoor) for other differences that might be relevant.

**Comment by HiteshR90** [comment]
@rothskeller thanks for sharing your source code i will check that. I can see in you code pod file doesn't contain pod 'RNStripeTerminal', :path => '../node_modules/react-native-stripe-terminal'.

But when I link this repo to project it's automatically added to pod file.

**Comment by rothskeller** [comment]
@HiteshR90 that is true.  I did not use "react-native link"; I linked RNStripeTerminal manually.  Perhaps that accounts for the difference?  See the README in my code for the exact steps I took.

**Comment by HiteshR90** [comment]
hi @rothskeller I am able to solve by link RnStripeTerminal by manually link.

Now I see another issue 
I my application is crashing in simulator mode
==========
Discovering readers...(from reader.js)
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-cor…:3 [React DevTools] Connection to RN closed

here from my app looks like StripeTerminal.addReadersDiscoveredListener is not getting called.
Can you please help on this?
Do I need to add anything in Info.plist? I have added below code. but still not working.
<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Bluetooth access is required to connect to the card reader.</string>
	<key>NSCameraUsageDescription</key>
	<string>Camera access is required to scan ticket barcodes.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Microphone access is required to connect to a card reader.</string>

but you application crash working fine in Simulator mode.
===
Discovering readers...
Discovered reader Simulator1
Connected to reader Simulator1

**Comment by JKazarian** [comment]
I am having the same problem as @HiteshR90

**Comment by theopolisme** [comment]
You may need to check the Header Search Paths for the RNStripeTerminal.a product and ensure that base/ios/Pods/Headers/Public/StripeTerminal is properly listed as a header search path - your error indicates that it is not currently finding the Stripe Terminal headers

**Comment by theopolisme** [comment]
I encountered an error somewhat like this when I did not properly return a token from the connection token function - did you ensure that was working properly?

Alteratively can you share your code so we can try to debug it?

**Comment by HiteshR90** [comment]
@theopolisme please find demo application which is not working for me.
https://github.com/HiteshR90/StripeTerminalDemo

**Comment by JKazarian** [comment]
@theopolisme im interested in seeing the solution to the issue that @HiteshR90 posted above

**Comment by JKazarian** [comment]
@theopolisme were you able to check the demo project from @HiteshR90 ?
