### ISSUE TITLE
Third parameter is missing in documentation while calling method discoverReaders()

### ISSUE THREAD

**Issue by ganesh-trabacus** [theopolisme/react-native-stripe-terminal#25]
I am following documentation and got error at funtiion discoderReaders() and after debugging found out third argument was missing which was expected to be float/Double value for which I gave random value then function proceeded further.

please update this repository according to stripe's latest code, and tell me which argument I should pass in `discoverReaders()`, so It will connect to reader-device.

```
StripeTerminal.discoverReaders(
                                    StripeTerminal.DeviceTypeChipper2X,
                                    StripeTerminal.DiscoveryMethodBluetoothProximity,
                                    123.456
                                );
```

**Comment by creakhead** [comment]
I think that last parameter is for simulated, and by putting in a number its treating it as true.  As i was struggling to get real data and tried this but looking at the results it seems like simulated data.

`[ { serialNumber: 'CHB20SIMULATOR1',
    batteryLevel: 0,
    deviceType: 0,
    deviceSoftwareVersion: '' },
  { serialNumber: 'CHB20SIMULATOR2',
    batteryLevel: 0,
    deviceType: 0,
    deviceSoftwareVersion: '' } ]`

**Comment by ganesh-trabacus** [comment]
Thanks for update, but I saw R terminal.java file and found out its 0 or 1, for telling true or false, is simulated or not.


If you want to check code working or not for real device connect me more I can screen share and show device listing to you.thanks for repo.






---- On Sat, 16 Nov 2019 04:07:34 +0530 notifications@github.com wrote ----



I think that last parameter is for simulated, and by putting in a number its treating it as true. As i was struggling to get real data and tried this but looking at the results it seems like simulated data.

[ { serialNumber: 'CHB20SIMULATOR1', batteryLevel: 0, deviceType: 0, deviceSoftwareVersion: '' }, { serialNumber: 'CHB20SIMULATOR2', batteryLevel: 0, deviceType: 0, deviceSoftwareVersion: '' } ]

**Comment by ganesh-trabacus** [comment]
I cleared that error, but now it's now working for `createPaymentIntent` and not calling that method.

please have a look.

**Comment by ganesh-trabacus** [comment]
also, @creakhead , if device is physical then we pass isSimulated=0(false), and then it isn't working.
