### ISSUE TITLE
React Native Expo support?

### ISSUE THREAD

**Issue by khuang-citylift** [theopolisme/react-native-stripe-terminal#32]
Hi theopolisme,

I am using Expo as my package manager for my React Native project. I do not have access to the native xcodeproj unless I detach/eject from Expo.

Do you have any ideas how I may get this working without performing the manual steps for iOS since I don't have the xcodeproj?

Thanks,
Kevin

**Comment by theopolisme** [comment]
Hey Kevin, thanks for reaching out. The Stripe Terminal SDK (i.e. the iOS SDK created by Stripe) is not included in Expo, so unfortunately there is nothing we can do here - you'll need to eject.
