### ISSUE TITLE
You must request location permissions before initializing the Terminal

### ISSUE THREAD

**Issue by EthanCents** [theopolisme/react-native-stripe-terminal#37]
Hello! 

I'm currently using this package to add Terminal functionality to my React Native app. I've added the package as a dependency, and have a `/terminal` endpoint in my backend to create a `connectionToken`, but when running StripeTerminal.initialize() I get the following warning:

`"You must request location permissions before initializing the Terminal"`

Have I not properly linked the native components, or is this something else I would need to do specifically within my Android or iOS code?

Anyone else having this issue?

**Comment by IvanTrutnev** [comment]
Hi, @EthanCents! How did you solve that issue?

**Comment by EthanCents** [comment]
@IvanTrutnev have you requested native location permissions for whatever device you're using?

**Comment by lordviet** [comment]
@IvanTrutnev For android devices you have to request permissions. 
```Javascript 
const requestPermissions = () =>
  PermissionsAndroid.requestMultiple([
    PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION,
    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
  ]);
```

**Comment by IvanTrutnev** [comment]
Much obliged @EthanCents  @lordviet
