### ISSUE TITLE
missing EventEmitter

### ISSUE THREAD

**Issue by rothskeller** [theopolisme/react-native-stripe-terminal#7]
I'm honestly not sure whether this is a library bug or a problem with my configuration.  But whenever I try to use this library in the iOS simulator, I get a failure:

```
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `EventEmitter` from `/Users/stever/src/orders/AtTheDoor/node_modules/react-native-stripe-terminal/connectionService.js`: Module `EventEmitter` does not exist in the Haste module map
```

`connectionService.js` has an `import EventEmitter from "EventEmitter"` line at the top, but as far as I can tell, no module `EventEmitter` exists.  Google searches suggest that there is one provided by Node, but that wouldn't help for client-side code, right?  I'm a bit fuzzy about it.

I've been able to work around this by changing the import to `import EventEmitter from 'eventemitter3'`.  The latter is a dependency of react-native so it's already in the configuration.

Is there something wrong with my configuration, or is there a real error here?  And if the latter, is my workaround the best fix?  I'm happy to open a PR for it if so.

**Comment by theopolisme** [comment]
This has been fixed in https://github.com/theopolisme/react-native-stripe-terminal/commit/1a6f503b895bfa640cfd357c58fa72adabf94119 - thanks!
