### ISSUE TITLE
Android integration

### ISSUE THREAD

**Issue by patmisch** [theopolisme/react-native-stripe-terminal#9]
Is anyone working on the android component yet? I'm considering tackling it, but will obviously hold off if someone else is already on it.

**Comment by theopolisme** [comment]
An Android integration would be awesome! To my knowledge no one has done anything on that front - would be awesome for you to start working on one.

**Comment by bradjones1** [comment]
@patmisch @theopolisme We are also interested in Android integration; it is unfortunately out of my development wheelhouse (I'm mostly a backend guy) but if either of you have some interest in sponsorship for bringing that to fruition, let me know by DM/email?

**Comment by patmisch** [comment]
It is slightly out of my wheelhouse as well. I can hack together an Android component, but it wouldn't be pretty. My company would also be willing to pay to have this done.

**Comment by bradjones1** [comment]
@theopolisme Any thoughts on sponsorship ^?

**Comment by patmisch** [comment]
@bradjones1 I may have someone who can get this done. Should know for sure by the end of the week.

**Comment by bradjones1** [comment]
@patmisch Interesting, thanks. And let me know if I can be of any assistance, whatever that looks like.

**Comment by bradjones1** [comment]
@patmisch Did you have any follow-up on whether you have a resource for this?

**Comment by patmisch** [comment]
@bradjones1 I should have something complete shortly. Hopefully early next week. Doing some internal testing currently.

**Comment by bradjones1** [comment]
@patmisch Oh wow, that's lovely news. Obviously interested to see what you've come up with and I am excited to assist with testing, or at least buying you a drink for your help!

**Comment by JKazarian** [comment]
@bradjones1 were you able to complete the testing and release it?

**Comment by patmisch** [comment]
@bradjones1 I still haven't been able to physically test... super busy. If you'd like to check out what we've got done, you can do so on our fork at https://github.com/passageinc/react-native-stripe-terminal

**Comment by bradjones1** [comment]
@patmisch OK cool - do you think you could open a PR against this project so we can track changes that way? I don't think I had permissions to open one given I don't own your branch. But the changes are visible through https://github.com/theopolisme/react-native-stripe-terminal/compare/master...passageinc:master - for anyone else looking to review.

I am going to go ahead and order a terminal to test this with myself - thanks for sponsoring the work on it, and hopefully I'll be able to help with testing soon.

**Comment by patmisch** [comment]
@bradjones1 Done.
